### ISSUE TITLE
Different pin?

### ISSUE THREAD

**Issue by jeffThompson** [shivasiddharth/pi-shut#2]
This is such a useful and fantastic project, thank you! I've already used it in an Airplay receiver and it works super well. However, I'm hoping to use it with another project that requires I2C and (I think) the default pin in your code is in conflict. 

If I wanted to use a different pin, would I just change it in `shutdown.py`? Any tips on picking a different pin I should be aware of?

**Comment by shivasiddharth** [comment]
You can change the shutdown pin to any other pin. The issue is the startup. The startup is by default assigned to Pin 5. Otherwise you need to have two buttons. One to start and other to shutdown. To start you can use the RUN pin on the board and some other to shutdown.

**Comment by jeffThompson** [comment]
Thanks for the quick reply! Seems such a bummer that this conflicts with the main I2C pins. Closing this with thanks for such a helpful tool!
